# Generated by Django 2.2.9 on 2020-08-05 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_url', models.CharField(max_length=512)),
                ('found_url', models.CharField(max_length=512)),
                ('job_title', models.CharField(max_length=512)),
                ('job_location', models.CharField(max_length=512)),
                ('short_description', models.CharField(max_length=512)),
                ('full_description', models.CharField(max_length=10000)),
                ('tags_string', models.CharField(max_length=512)),
                ('seen_time_epoch', models.IntegerField(default=0)),
                ('job_relevant', models.BooleanField(default=True)),
                ('scraping_task_desc', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='JobSearchInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(default=0)),
                ('job_search_title', models.TextField()),
                ('initial_keywords', models.TextField(default='')),
                ('job_search_description', models.TextField(default='')),
                ('user_job_id', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('server_with_port', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='JobSearchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('user_id', models.PositiveIntegerField(default=0)),
                ('user_job_id', models.PositiveIntegerField(default=0)),
                ('job_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.JobDescription')),
                ('job_search_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.JobSearchInfo')),
            ],
        ),
        migrations.CreateModel(
            name='JobDescriptionSeenTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_seen_time_epoch', models.IntegerField(default=0)),
                ('last_seen_time_epoch', models.IntegerField(default=0)),
                ('job_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.JobDescription')),
            ],
        ),
    ]
