# Generated by Django 3.0.8 on 2020-09-30 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdescriptionseentimes',
            name='job_description',
        ),
        migrations.RemoveField(
            model_name='jobsearchresult',
            name='job_description',
        ),
        migrations.RemoveField(
            model_name='jobsearchresult',
            name='job_search_info',
        ),
        migrations.DeleteModel(
            name='UserToken',
        ),
        migrations.DeleteModel(
            name='JobDescriptionSeenTimes',
        ),
        migrations.DeleteModel(
            name='JobSearchResult',
        ),
    ]
